#cloud-config
users:
  - name: ${username}
    gecos: Emergency user
    lock_passwd: true
    shell: ${shell}
    groups: ${groups}
    sudo: ${sudo}
    ssh-authorized-keys:
      - ${public_key_file}
